# Generated by Django 6.0.2 on 2026-03-03 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='lead_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_status',
            field=models.CharField(default='New', max_length=20),
        ),
    ]
