# Generated by Django 6.0.2 on 2026-03-07 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_lead_score_lead_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='lead_status',
            field=models.CharField(default='Cold', max_length=20),
        ),
    ]
