# Generated by Django 4.2 on 2026-03-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_alter_lead_lead_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
